name: Tests
on:
  push:
    branches:
      - main
      - develop

jobs:
    test:
        # Define the job named "test" that will run on the latest Ubuntu environment
        runs-on: ubuntu-latest
        steps:
            # Step 1: Check out the repository code
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                python-version: '3.13.1'  # Specify the Python version to use
            # Step 2: Set up Python 3.8 environment
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip  # Upgrade pip to the latest version
                pip install pytest-playwright        # Install dependencies from requirements.txt
            # Step 3: Ensure browser binaries are installed
            - name: Install browsers
              run:  python -m playwright install chromium  --with-deps  # Install Playwright browsers and dependencies
            # Step 4: Run tests using pytest
            - name: Run tests
              run: |
                # Run tests using pytest with short output and disabling warnings
                cd cubeit   # Change directory to the cubeit folder
                python -m http.server 8001 &  
                cd ..
                pytest -v 